// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ToGomp(arg1) {
  return window['go']['main']['App']['ToGomp'](arg1);
}
